from pydantic import BaseModel, Field
from typing import List, Literal, Optional
from datetime import datetime

from chimera.models.evidence import Evidence

HypothesisStatus = Literal['proposed', 'testing', 'confirmed', 'rejected']

class Hypothesis(BaseModel):
    '''\n    The central object of Chimera.\n    \n    Everything revolves around generating, testing, and validating hypotheses.\n    A hypothesis is not a finding — it is a falsifiable claim about the target.\n    '''\n    id: str = Field(description='Unique hypothesis identifier')\n    claim: str = Field(description='The falsifiable claim, e.g. \"The application is vulnerable to SQL injection\"')\n    \n    required_conditions: List[str] = Field(\n        default_factory=list,\n        description='What must be true for this claim to hold'\n    )\n    \n    evidence: List[Evidence] = Field(\n        default_factory=list,\n        description='Observations that support the claim'\n    )\n    \n    missing_information: List[str] = Field(\n        default_factory=list,\n        description='What we still need to know to decide'\n    )\n    \n    falsifiers: List[str] = Field(\n        default_factory=list,\n        description='What observations would prove this claim false'\n    )\n    \n    confidence: float = Field(\n        ge=0.0, le=1.0, default=0.0,\n        description='Current belief strength based on evidence and gaps'\n    )\n    \n    status: HypothesisStatus = Field(default='proposed')\n    \n    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())\n    updated_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())\n    \n    def add_evidence(self, evidence: Evidence) -> 'Hypothesis':\n        self.evidence.append(evidence)\n        self.updated_at = datetime.utcnow().isoformat()\n        return self\n    \n    def check_completeness(self) -> float:\n        '''\n        How complete is our evidence relative to required conditions?\n        1.0 = all required conditions have evidence\n        0.0 = no required conditions have evidence\n        '''\n        if not self.required_conditions:\n            return 0.0\n        # Simple heuristic: count evidence sources matching conditions\n        # TODO: make this semantic\n        return min(1.0, len(self.evidence) / max(1, len(self.required_conditions)))\n    \n    def is_falsified(self) -> bool:\n        '''Check if any evidence directly contradicts the claim.'''\n        # TODO: implement contradiction detection\n        return False
